### PR TITLE
Fix: small issues

### PR DESCRIPTION
**Pull request by pwltr**
- use hostname from env var for development, fallback in vite config
- fix sdk import syntax
- use fast polling in development
- fix: some types
- Fix sidebar "jumping" when navigating to AppStore 
Screenshot_20220615_141710

### CODE REVIEW

**Review by AaronDewes — DISMISSED** [review]
Please fix the merge conflicts

**Comment by pwltr** [comment]
This is still a draft for now. I'll add some more bug fixes and then rebase everything.

**Comment by pwltr** [comment]
You can review this now. I tried to get a fix in for the FeeSelector and `@vue/compat` bugs but no dice...

**Review by AaronDewes — APPROVED** [review]
No worries, I'm working on something better to solve the Vue issues anyway

**Review by WilliamConnatser — APPROVED** [review]

**Pull request merged**
