### PR TITLE
Port to TypeScript & Pinia

### PR DESCRIPTION
**Pull request by AaronDewes**
This also switches from Vuex to Pinia

### CODE REVIEW

**Comment by AaronDewes** [comment]
@pwltr I merged your Docker improvements here, are you okay with that?

**Comment by pwltr** [comment]
> @pwltr I merged your Docker improvements here, are you okay with that?

That shouldn't cause any problems. I'll start testing this branch now.

**Comment by AaronDewes** [comment]
@pwltr Does this look okay to you now?

**Review by pwltr — APPROVED** [review]
Looks good, clicking through the dashboard not seeing any errors.

**Pull request merged**
