### PR TITLE
Replace favicon + sats/btc input not correctly aligned

### PR DESCRIPTION
**Pull request by mateitudose**
Just another small fix, child div need to be a flex item, otherwise "align-self" has no effect. Favicon was also replaced with the Citadel logo.

bug

### CODE REVIEW

**Comment by mateitudose** [comment]
There is also a fix for dark mode on mobile 
vertical_bug

**Review by AaronDewes — APPROVED** [review]

**Comment by AaronDewes** [comment]
Thanks a lot!

**Comment by AaronDewes** [comment]
I'll include this on Citadel 0.5.2

**Comment by mateitudose** [comment]
Sure, it's up to you when :)

**Pull request merged**
